name: 'Generate PR Comment from TF Plans'
description: 'Download tfplan JSON artifacts and generate PR comments using go-tfplan-commenter'
author: 'akomic'

inputs:
  password:
    description: 'Password for decrypting artifacts'
    required: true
  output-file:
    description: 'Output file for the generated comment'
    required: false
    default: 'comment.md'
  post-comment:
    description: 'Whether to post the comment to the PR'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token for posting comments'
    required: false
    default: ${{ github.token }}

outputs:
  comment-file:
    description: 'Path to the generated comment file'
    value: ${{ steps.generate.outputs.comment-file }}

runs:
  using: 'composite'
  steps:
    - id: temp
      shell: bash
      run:
        echo "temp=${RUNNER_TEMP}" >> $GITHUB_OUTPUT

    - name: Try download consolidated artifact
      id: download-consolidated
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      continue-on-error: true
      with:
        name: tfplan-collection
        path: ${{ steps.temp.outputs.temp }}/consolidated-artifact

    - name: Download individual artifacts if no consolidated
      if: steps.download-consolidated.outcome == 'failure'
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        path: ${{ steps.temp.outputs.temp }}/individual-artifacts
        pattern: tfplan-collection-*
        merge-multiple: false

    - name: Decrypt and organize tfplan files
      id: generate
      shell: bash
      run: |
        mkdir -p ${{ steps.temp.outputs.temp }}/tfplan-artifacts
        
        if [ "${{ steps.download-consolidated.outcome }}" == "success" ]; then
          echo "Using consolidated artifact"
          encrypted_file=$(find ${{ steps.temp.outputs.temp }}/consolidated-artifact -name "*.tar.7z" | head -1)
          if [ -n "$encrypted_file" ]; then
            7z x -p"${{ inputs.password }}" "$encrypted_file" -so | tar xf - -C ${{ steps.temp.outputs.temp }}/tfplan-artifacts/
          fi
        else
          echo "Using individual artifacts"
          for artifact_dir in ${{ steps.temp.outputs.temp }}/individual-artifacts/tfplan-collection-*; do
            if [ -d "$artifact_dir" ]; then
              encrypted_file=$(find "$artifact_dir" -name "*.tar.7z" | head -1)
              if [ -n "$encrypted_file" ]; then
                7z x -p"${{ inputs.password }}" "$encrypted_file" -so | tar xf - -C ${{ steps.temp.outputs.temp }}/tfplan-artifacts/
              fi
            fi
          done
        fi
        
        find ${{ steps.temp.outputs.temp }}/tfplan-artifacts/ -type f
        if [ ! -d "${{ steps.temp.outputs.temp }}/tfplan-artifacts" ]; then
          echo "No tfplan artifacts found"
          exit 0
        fi

        tf-plan-commenter ${{ steps.temp.outputs.temp }}/tfplan-artifacts/ ${{ inputs.output-file }}
        
    - name: Post PR comment
      if: inputs.post-comment == 'true' && github.event_name == 'pull_request'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -f "${{ inputs.output-file }}" ]; then
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Posting comment to PR #${PR_NUMBER}"
          gh pr comment "$PR_NUMBER" --body-file ./${{ inputs.output-file }}
        else
          echo "Comment file not found, skipping PR comment"
        fi
