name: 'Install Terraform, Terragrunt, and TF Plan Commenter'
description: 'Install and cache Terraform, Terragrunt, and go-tfplan-commenter binaries'
author: 'akomic'

inputs:
  terraform-version:
    description: 'Terraform version to install, "none" to skip installation'
    required: false
    default: '1.9.8'
  terragrunt-version:
    description: 'Terragrunt version to install, "none" to skip installation'
    required: false
    default: '0.83.2'
  tf-commenter-version:
    description: 'TF Plan Commenter version to install, "none" to skip installation'
    required: false
    default: '1.1.0'

outputs:
  cache-key:
    description: 'Cache key used for the installed binaries'
    value: ${{ steps.set-cache-key.outputs.cache-key }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache-binaries.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Set cache key
      id: set-cache-key
      shell: bash
      run: echo "cache-key=local-bin-${{ runner.os }}-${{ inputs.terraform-version }}-${{ inputs.terragrunt-version }}-${{ inputs.tf-commenter-version }}" >> $GITHUB_OUTPUT

    - name: Cache installed binaries
      id: cache-binaries
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.local/bin
        key: local-bin-${{ runner.os }}-${{ inputs.terraform-version }}-${{ inputs.terragrunt-version }}-${{ inputs.tf-commenter-version }}

    - name: Install dependencies
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      shell: bash
      run: |
        CWD=$(pwd)

        mkdir -p "$HOME/.local/bin"

        # Terragrunt install
        if [ "${{ inputs.terragrunt-version }}" != "none" ]; then
          echo "Installing terragrunt version ${{ inputs.terragrunt-version }}"
          curl -sL "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt-version }}/terragrunt_linux_amd64" -o "$HOME/.local/bin/terragrunt"
          chmod +x "$HOME/.local/bin/terragrunt"
        else
          echo "Skipping terragrunt installation"
        fi

        # Terraform install
        if [ "${{ inputs.terraform-version }}" != "none" ]; then
          echo "Installing terraform version ${{ inputs.terraform-version }}"
          mkdir -p $RUNNER_TEMP/tf-install
          cd $RUNNER_TEMP/tf-install
          curl -sL -o terraform.zip https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_amd64.zip
          unzip terraform.zip terraform
          mv terraform "$HOME/.local/bin/"
          cd $CWD
          chmod +x "$HOME/.local/bin/terraform"
        else
          echo "Skipping terraform installation"
        fi

        # TF plan PR commenter
        if [ "${{ inputs.tf-commenter-version }}" != "none" ]; then
          echo "Installing tfplan-commenter version ${{ inputs.tf-commenter-version }}"
          curl -sL https://github.com/akomic/go-tfplan-commenter/releases/download/v${{ inputs.tf-commenter-version }}/tfplan-commenter-linux-amd64 -o "$HOME/.local/bin/tf-plan-commenter"
          chmod +x "$HOME/.local/bin/tf-plan-commenter"
        else
          echo "Skipping tfplan-commenter installation"
        fi

        echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV
        echo "TF_INPUT=false" >> $GITHUB_ENV
        echo "TG_QUEUE_INCLUDE_EXTERNAL=false" >> $GITHUB_ENV
        echo "TG_QUEUE_EXCLUDE_EXTERNAL=true" >> $GITHUB_ENV
        echo "TG_NON_INTERACTIVE=true" >> $GITHUB_ENV

    - name: Add binaries to PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
